on:
  release:  # only on releases
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.0

      - name: Setup nodeJS ğŸ§©
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Build ğŸ”§
        run: npm ci

      - name: Publish sğŸš€
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
